name: build
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: android-actions/setup-android@v2
      - uses: gradle/gradle-build-action@v2
      - run: |
          mkdir -p app/libs
          wget -O app/libs/libbox.aar https://github.com/NickCao/sing-box/releases/download/latest/libbox.aar
          ./gradlew build
